template done
CodeTheChangeUBC/redcross pull request #11
Opened 2017-11-14 21:30 UTC by JustinZhengBC

i changed something in global.css to allow scrolling

2017-11-15 04:56 UTC, tomyang729 commented
Good job overall!

I found a few bugs when I test it on my browser:
1. Unhandled error showing in the console. (somthing like 'title of undefined')
2. The matCard component seems like not having responsive styling. (If you type in a very long text, and then shrink the screen, the text are out of box)
3. The matDialogContainer modal should also have responsive width.

@omzmarlon

2017-11-25 07:28 UTC, omzmarlon commented
@JustinZhengBC I've just got some time to look at yours and Madeleine's code. Since you guys code are similar,  take a look at my comments in Madeleine's PR and then apply similar changes to your code so that I don't have to repeat myself : )

2017-12-12 05:48 UTC, JustinZhengBC commented
I fixed the resizing issues and got rid of the "title of undefined" error that happens when you cancel a new post instead of submitting it. I also reorganized code according to the comments in Madeleine's PR where appropriate.

2017-12-16 06:18 UTC, omzmarlon requested changes
Also use nesting in .less files to better reflect structures in html

2017-12-16 06:18 UTC, omzmarlon commented on web/src/redcross/discussionModule/components/DiscussionComponent.ts
> +    constructor(private dds: DiscussionDataService,
Rename this component to DiscussionContainerComponent. Also rename the html and less

Also move the AddPostDialog class into a separate file

2017-12-20 01:11 UTC, JustinZhengBC commented
Not sure if I did the nesting properly, but lint doesn't have any problems with it

2018-01-02 18:21 UTC, omzmarlon approved these changes

2018-01-02 18:21 UTC, omzmarlon commented
Good job!

2018-01-02 18:21 UTC, merged