Basic templating for blogs
CodeTheChangeUBC/redcross pull request #12
Opened 2017-11-22 06:57 UTC by madeleinefrancis

Still having trouble with sizing of the mat-dialog used for blogDialog components when in mobile view... not sure where it's inheriting its small size from. I'll expand the post class to include photos once I know how that will work with you guys.

2017-11-22 19:20 UTC, omzmarlon commented
Good Work! I'll take a look ASAP

2017-11-25 07:19 UTC, omzmarlon requested changes
@madeleinefrancis 
Just took a look. You've done great work! : )
A few comments:
1. I have a cannot read title of undefined in my browser console, when I navigate to http://localhost:8000/#/blogs/postTest
2. Great that you've spot a need for model classes like Post.ts and Author.ts. 
But I would suggest creating a new folder inside blogModule called "models" and then move these to there
3. The MatDialogModule you imported in BlogModule.ts, since many different modules will need MatDialog, so I would suggest move it there, and any other modules from Angular Material. This will probably cause conflict with other people's code when you merge to master. But we can deal with that later
4. I'm not sure why you added child routes to BlogRoutingModule?
5. For the add button, you can use MatIcon from Angular material, sth like:
`<button md-fab><md-icon>add</md-icon></button>`
The icon should work once you use them, since I think've add a link to get icons globally in index.html. If your code can't find the icon, let me know
6. Same for services. Create a folder called "services" and move the BlogDataService there
7. rename BlogComponent to BlogContainerComponent
8. for all of your less files, use nesting to better reflect structures in html. eg: in Blog.less, move everything inside .blog-outer
9. other comments are with the code

I might have just a few other things to say(about photos and structuring container and children components), but fix these first we can discuss the rest after that!

2017-11-25 07:19 UTC, omzmarlon commented on web/src/redcross/blogModule/components/BlogComponent.ts
> +        private addPost(): void {
this line not properly formatted

2017-11-25 07:19 UTC, omzmarlon commented on web/src/redcross/blogModule/components/BlogComponent.ts
> +        private ngOnInit(): void {
this line not properly formatted

2017-11-25 07:19 UTC, omzmarlon commented on web/src/redcross/blogModule/components/BlogDataService.ts
> +export class DiscussionDataService {
make your class name match file name. And also why is it called discussion?

2017-11-25 07:19 UTC, omzmarlon commented on web/src/redcross/blogModule/components/BlogComponent.ts
> +import {MatDialog, MatDialogRef, MAT_DIALOG_DATA} from "@angular/material";
remove unused imports

2017-11-25 07:19 UTC, omzmarlon commented on web/src/redcross/blogModule/components/BlogComponent.ts
> +    constructor(public dds: DiscussionDataService, public md: MatDialog) {}
these should be private. If you do intend to let other classes to use them, always make them private! Check other classes constructor too!

2017-12-16 06:25 UTC, omzmarlon commented
Not nesting styles in BlogDialog.less
You add button's icon is not working. And also has a really weird box shadow. 
When I try to add a new blog, an error is thrown. 
See below picture:
<img width="1276" alt="aaa" src="https://user-images.githubusercontent.com/13238492/34067899-d1c24114-e1e6-11e7-9b4d-6a6841de35dc.png">

2017-12-16 21:58 UTC, madeleinefrancis commented
So not sure if using <i class="material-icons"> to get the icon working is okay but having trouble getting it to show with <md-icon>

2017-12-16 22:00 UTC, madeleinefrancis commented
Not sure if its desirable but I was having trouble getting the icon to show with md-icon so I ended up using class="material-icons" in an "i" element.

2017-12-16 22:02 UTC, madeleinefrancis commented
Also just added a background color to the icon button because it becomes barely visible in mobile view but I guess we will probably change the styles later anyways.

2018-01-02 18:16 UTC, omzmarlon requested changes
There's just one more small problem with the create new blog post form. When I click cancel, a new blog post was still created and added to the list

2018-01-02 18:16 UTC, omzmarlon commented on web/src/redcross/blogModule/components/Blog.ng.html
> +    <button md-fab class="add-post-button" (click)="addPost()">
You can add button by using the mat-icon-button with mat-icon nested inside. Something like:
`<button mat-icon-button>
<mat-icon>add</mat-icon>
</button>`
Using mat-icon, Angular Material should automatically load

2018-01-02 18:24 UTC, omzmarlon commented on web/src/redcross/blogModule/components/Blog.ng.html
> +    <button md-fab class="add-post-button" (click)="addPost()">
Or, if you really can't figure it out, checkout  Justin's code. He basically put a '+' sign there. 
This is not the best approach, but we can change that later.
His code is already merged to master.

2018-01-07 06:40 UTC, omzmarlon approved these changes

2018-01-07 06:40 UTC, merged

2018-01-07 06:41 UTC, omzmarlon commented
Good job!